# Generated by Django 6.0 on 2026-01-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_at',
            field=models.DateTimeField(),
        ),
    ]
