# Generated by Django 6.0 on 2026-01-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_app', '0002_alter_user_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
