# Generated by Django 6.0 on 2026-01-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_app', '0003_alter_user_joined_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming_app.user')),
            ],
        ),
    ]
