# Generated by Django 6.0 on 2026-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_app', '0004_gameplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_game',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
