# Generated by Django 6.0 on 2026-01-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_app', '0005_user_favorite_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplay',
            name='play_duration',
            field=models.IntegerField(default=0),
        ),
    ]
