# Generated by Django 6.0 on 2026-01-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_app', '0006_gameplay_play_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_game',
        ),
        migrations.CreateModel(
            name='FavoriteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='gaming_app.user')),
            ],
            options={
                'unique_together': {('user', 'game_name')},
            },
        ),
    ]
